export default [
    {"response":"only_me", "id":"whoiam"},
    {"response":"me_and_some_others", "id":"whoiam2"},
    {"response":"others_but_not_me","id":"whoiam3"},
    {"response":"attendee_and_decision_maker", "id":"payer_1"},
    {"response":"attendee_but_not_decision_maker", "id":"payer_1"},
    {"response":"decision_maker", "id":"payer_1"},
    {"response":"asker_but_not_decision_maker", "id":"payer_1"},
    {"response":"i_pay", "id":"how_you_pay_1"},
    {"response":"my_company_pay", "id":"how_company_pay_1"},
    {"response":"organism_pay", "id":"what_organism_pay_1"},
    {"response":"i_dont_know_who_pay", "id":"how_many_attendees"},
    {"response":"i_pay_with_my_money", "id":"what_amount_will_you_pay"},
    {"response":"i_pay_with_my_cpf", "id":"what_cpf_amount_will_you_pay"},
    {"response":"i_dont_know_if_my_company_will_ask_payer_organism", "id":"how_many_attendees"},
    {"response":"my_company_will_ask_payer_organism", "id":"what_organism_pay"},
    {"response":"organism_name", "id":"how_many_attendees"},
    {"response":"i_dont_know_organism_name", "id":"how_many_attendees"},
    {"response":"budget", "id":"how_many_attendees"},
]
